version: 2

project_name: qpack

builds:
  - id: qpack
    main: ./cmd
    goos: [linux, windows]
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - readme.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
